version: 0.2
env:
  variables:
    APP_NAME: "champion-mvp-dev"
phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo install process started
      - npm install --legacy-peer-deps && npm install -g @angular/cli && npm install aws-cdk -g
  build:
    commands:
      - echo ng build process started
      - ng build --configuration=dev
      - echo ng build success
      - cdk synth --quiet
  post_build:
    commands:
      - echo build process finished!
      - ls -la
      # - ls -la ./dist
      # - ls -la ./dist/$APP_NAME
      - ls -la ./dist/$APP_NAME/browser
      - ls -la ./cdk.out/
      # - aws s3 sync ./dist/$APP_NAME/browser s3:// --delete
artifacts:
  name: 'FitNest-Ng'
  base-directory: './dist/$APP_NAME/browser'
    # secondary-artifacts:
    # cdk-template:
    # files:
  # - '/cdk.out/CdkStack.template.json'