export enum MotionEnum {
  FLEXION = "FLEXION",
  ABDUCTION = "ABDUCTION",
  INTERNAL_ROTATION = "INTERNAL_ROTATION",
  EXTERNAL_ROTATION = "EXTERNAL_ROTATION",
  EXTENSION = "EXTENSION",
  LATERAL_FLEXION = "LATERAL_FLEXION",
}
